apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: grafana
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io