apiVersion: extensions/v1beta1
kind: Deployment
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: kube-system
  labels:
    app: rabbitmq  
spec:
  podManagementPolicy: Parallel
  serviceName: rabbitmq
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      containers:
      - name: rabbitmq
        image: registry.chinadaas.com/kubernetes/rabbitmq:v0.1
#        image: registry.chinadaas.com/kubernetes/rabbitmq-autocluster:v3.6.12-0.1
        ports:
          - containerPort: 5672
            name: rabbitmq-5672
          - containerPort: 4369
            name: rabbitmq-4369
          - containerPort: 5671
            name: rabbitmq-5671
          - containerPort: 15672
            name: rabbitmq-15672
          - containerPort: 25672
            name: rabbitmq-25672
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: AUTOCLUSTER_CLEANUP
            value: "true"
          - name: CLEANUP_INTERVAL
            value: "60"
          - name: CLEANUP_WARN_ONLY
            value: "false"
          - name: AUTOCLUSTER_DELAY
            value: "30"
          # start.sh will store this value to a proper location in filesystem
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: erlang.cookie
                key: erlang.cookie
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 5
        volumeMounts:
        - name: rabbitmq-vol-1
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-vol-1
        hostPath:
          path: /data/rabbitmq/
