apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: rabbitmq-5672
    protocol: TCP
    targetPort: 5672    
  - port: 4369
    name: rabbitmq-4369
    protocol: TCP
    targetPort: 4369    
  - port: 5671
    name: rabbitmq-5671
    protocol: TCP
    targetPort: 5671    
  - port: 15672
    name: rabbitmq-15672
    nodePort: 15672
    protocol: TCP
    targetPort: 15672    
  - port: 25672
    name: rabbitmq-25672
    protocol: TCP
    targetPort: 25672    
