apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: rabbitmq
subjects:
  - kind: ServiceAccount
    name: rabbitmq
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
