apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-monitoring
    version: v1.7.0
  name: prometheus-monitoring
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-monitoring
  template:
    metadata:
      name: prometheus-monitoring
      labels:
        app: prometheus-monitoring
    spec:
      containers:
      # Prometheus server
      - name: prometheus
        image: registry.chinadaas.com/kubernetes/prometheus
        args:
          - '-storage.local.retention=72h'
          - '-storage.local.path=/home'
          - '-storage.local.memory-chunks=10485760'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://localhost:9093'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus
        - name: config-volume-alert-rules
          mountPath: /etc/prometheus-rules
        - name: prometheus-data
          mountPath: /home
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 400Mi

      #Alert manager
      - name: alertmanager
        image: registry.chinadaas.com/kubernetes/alertmanager
        args:
          - -config.file=/etc/prometheus/alertmanager.yml
        volumeMounts:
        - name: config-volume-alertmanager
          mountPath: /etc/prometheus

      # Volumes and config maps
      volumes:
      - name: config-volume-prometheus
        configMap:
          name: prometheus
      - name: config-volume-alertmanager
        configMap:
          name: prometheus-alertmanager
      - name: config-volume-alert-rules
        configMap:
          name: prometheus-alert-rules
      - name: prometheus-data
        hostPath:
          path: /monitoring/prometheus-data

#      nodeSelector:
#        prometheus: "true"
