apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus-monitoring
  name: prometheus-monitoring
  namespace: kube-system
spec:
  selector:
    app: prometheus-monitoring
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 9090
