apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-cluster
  namespace: kube-system
subsets:
  - addresses:
    - ip: 192.168.61.71
    - ip: 192.168.61.72
    - ip: 192.168.61.73
    ports:
    - port: 2379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  namespace: kube-system
spec:
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
